### ISSUE TITLE
请问为什么这个会报错RandomForest是一个未命名类型呢？

### ISSUE THREAD

**Issue by Dong6971** [IMRL/ActiveLoopClosure#2]
![image](https://github.com/user-attachments/assets/d9ebd32a-32bd-489d-9077-791d9e1a67eb)
![image](https://github.com/user-attachments/assets/1a8162a1-7a14-4e1e-abca-cabb36a0196b)
代码都是从github上面下载回来的，没有更改
麻烦指教一下，感谢作者！

**Comment by GOD-VV** [comment]
看报错应该是你ceres版本和mlpack的问题，请问项目依赖有正确安装吗？

**Comment by Dong6971** [comment]
![image](https://github.com/user-attachments/assets/9ae8fdb8-b05a-45c0-becf-18f36a23d0c3)
![image](https://github.com/user-attachments/assets/0e94b079-3468-413d-acac-d0147646c647)

两个依赖包都是已经安装了的，并且这个mlpack/methods/random_forest/random_forest.hpp也是可以找得到的

**Comment by IMRL** [comment]
配置文件里没有include随机深林的路径？


________________________________

**Comment by Dong6971** [comment]
![image](https://github.com/user-attachments/assets/f73ebcb1-25d6-45d8-9a04-a33569993633)
![image](https://github.com/user-attachments/assets/eb7e3120-ff74-4d88-ad30-c9103b6e71f5)
我有尝试过把这个注释解除掉，但是它会报上面这个错，是不是需要在cmakelists文件中直接指定MLPACK的路径？

**Comment by GOD-VV** [comment]
可以尝试从源代码中安装mlpack，readme中有放置mlpack的链接

**Comment by Dong6971** [comment]
![image](https://github.com/user-attachments/assets/ce2cdf6d-d02a-4598-bd49-f792cda2294b)
使用源码安装了ceres以及mlpack库，已经编译通过了，感谢作者的回答！
